#############################################################################
# Makefile for building: build/release/platformowka
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  platformowka.pro
# Template: app
# Command: /home/maciej/Qt/5.5/gcc_64/bin/qmake -o Makefile platformowka.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=c++0x -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/maciej/Qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = platformowka1.0.0
DISTDIR = /home/maciej/platformowka/.tmp/platformowka1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/maciej/Qt/5.5/gcc_64
LIBS          = $(SUBLIBS) -lSDL2main -lSDL2 -lSDL2_ttf -lGL -lGLU -lGLEW 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		App.cpp \
		Camera2D.cpp \
		Errors.cpp \
		GameScreen.cpp \
		GLSLProgram.cpp \
		ImageLoader.cpp \
		InputManager.cpp \
		IOManager.cpp \
		Level.cpp \
		MenuButton.cpp \
		MenuScreen.cpp \
		picoPNG.cpp \
		Player.cpp \
		ResourceManager.cpp \
		Sprite.cpp \
		SpriteBatch.cpp \
		SpriteFont.cpp \
		TextureCache.cpp \
		Timer.cpp \
		Window.cpp \
		MultiScreen.cpp 
OBJECTS       = main.o \
		App.o \
		Camera2D.o \
		Errors.o \
		GameScreen.o \
		GLSLProgram.o \
		ImageLoader.o \
		InputManager.o \
		IOManager.o \
		Level.o \
		MenuButton.o \
		MenuScreen.o \
		picoPNG.o \
		Player.o \
		ResourceManager.o \
		Sprite.o \
		SpriteBatch.o \
		SpriteFont.o \
		TextureCache.o \
		Timer.o \
		Window.o \
		MultiScreen.o
DIST          = platformowka.pro.user \
		Sieci \
		Platformowka.vcxproj \
		Sieci \
		Platformowka.vcxproj.filters \
		Sieci \
		Platformowka.vcxproj.user \
		../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../Qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		platformowka.pro App.h \
		Camera2D.h \
		Errors.h \
		GameScreen.h \
		GLSLProgram.h \
		GLTexture.h \
		ImageLoader.h \
		InputManager.h \
		IOManager.h \
		Level.h \
		MenuButton.h \
		MenuScreen.h \
		picoPNG.h \
		Player.h \
		ResourceManager.h \
		Sprite.h \
		SpriteBatch.h \
		SpriteFont.h \
		TextureCache.h \
		Timer.h \
		Vertex.h \
		Window.h \
		MultiScreen.h main.cpp \
		App.cpp \
		Camera2D.cpp \
		Errors.cpp \
		GameScreen.cpp \
		GLSLProgram.cpp \
		ImageLoader.cpp \
		InputManager.cpp \
		IOManager.cpp \
		Level.cpp \
		MenuButton.cpp \
		MenuScreen.cpp \
		picoPNG.cpp \
		Player.cpp \
		ResourceManager.cpp \
		Sprite.cpp \
		SpriteBatch.cpp \
		SpriteFont.cpp \
		TextureCache.cpp \
		Timer.cpp \
		Window.cpp \
		MultiScreen.cpp
QMAKE_TARGET  = platformowka
DESTDIR       = build/release/#avoid trailing-slash linebreak
TARGET        = build/release/platformowka


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d build/release/ || mkdir -p build/release/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: platformowka.pro ../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf ../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../Qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		platformowka.pro
	$(QMAKE) -o Makefile platformowka.pro
../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
../Qt/5.5/gcc_64/mkspecs/common/unix.conf:
../Qt/5.5/gcc_64/mkspecs/common/linux.conf:
../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
../Qt/5.5/gcc_64/mkspecs/qconfig.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
../Qt/5.5/gcc_64/mkspecs/features/default_post.prf:
../Qt/5.5/gcc_64/mkspecs/features/c++11.prf:
../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
../Qt/5.5/gcc_64/mkspecs/features/yacc.prf:
../Qt/5.5/gcc_64/mkspecs/features/lex.prf:
platformowka.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile platformowka.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp App.h \
		MenuScreen.h \
		Camera2D.h \
		SpriteBatch.h \
		Vertex.h \
		GLSLProgram.h \
		Window.h \
		Timer.h \
		SpriteFont.h \
		MenuButton.h \
		InputManager.h \
		GameScreen.h \
		Player.h \
		ResourceManager.h \
		TextureCache.h \
		GLTexture.h \
		Level.h \
		MultiScreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

App.o: App.cpp App.h \
		MenuScreen.h \
		Camera2D.h \
		SpriteBatch.h \
		Vertex.h \
		GLSLProgram.h \
		Window.h \
		Timer.h \
		SpriteFont.h \
		MenuButton.h \
		InputManager.h \
		GameScreen.h \
		Player.h \
		ResourceManager.h \
		TextureCache.h \
		GLTexture.h \
		Level.h \
		MultiScreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o App.o App.cpp

Camera2D.o: Camera2D.cpp Camera2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Camera2D.o Camera2D.cpp

Errors.o: Errors.cpp Errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Errors.o Errors.cpp

GameScreen.o: GameScreen.cpp GameScreen.h \
		Camera2D.h \
		SpriteBatch.h \
		Vertex.h \
		GLSLProgram.h \
		Window.h \
		Timer.h \
		Player.h \
		ResourceManager.h \
		TextureCache.h \
		GLTexture.h \
		InputManager.h \
		Level.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameScreen.o GameScreen.cpp

GLSLProgram.o: GLSLProgram.cpp GLSLProgram.h \
		Errors.h \
		IOManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLSLProgram.o GLSLProgram.cpp

ImageLoader.o: ImageLoader.cpp ImageLoader.h \
		GLTexture.h \
		picoPNG.h \
		IOManager.h \
		Errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageLoader.o ImageLoader.cpp

InputManager.o: InputManager.cpp InputManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputManager.o InputManager.cpp

IOManager.o: IOManager.cpp IOManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IOManager.o IOManager.cpp

Level.o: Level.cpp Level.h \
		Vertex.h \
		ResourceManager.h \
		TextureCache.h \
		GLTexture.h \
		SpriteBatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Level.o Level.cpp

MenuButton.o: MenuButton.cpp MenuButton.h \
		Vertex.h \
		SpriteBatch.h \
		SpriteFont.h \
		ResourceManager.h \
		TextureCache.h \
		GLTexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MenuButton.o MenuButton.cpp

MenuScreen.o: MenuScreen.cpp MenuScreen.h \
		Camera2D.h \
		SpriteBatch.h \
		Vertex.h \
		GLSLProgram.h \
		Window.h \
		Timer.h \
		SpriteFont.h \
		MenuButton.h \
		InputManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MenuScreen.o MenuScreen.cpp

picoPNG.o: picoPNG.cpp picoPNG.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o picoPNG.o picoPNG.cpp

Player.o: Player.cpp Player.h \
		Vertex.h \
		ResourceManager.h \
		TextureCache.h \
		GLTexture.h \
		InputManager.h \
		SpriteBatch.h \
		Level.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cpp

ResourceManager.o: ResourceManager.cpp ResourceManager.h \
		TextureCache.h \
		GLTexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ResourceManager.o ResourceManager.cpp

Sprite.o: Sprite.cpp Sprite.h \
		GLTexture.h \
		Vertex.h \
		ResourceManager.h \
		TextureCache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sprite.o Sprite.cpp

SpriteBatch.o: SpriteBatch.cpp SpriteBatch.h \
		Vertex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpriteBatch.o SpriteBatch.cpp

SpriteFont.o: SpriteFont.cpp SpriteFont.h \
		Vertex.h \
		SpriteBatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpriteFont.o SpriteFont.cpp

TextureCache.o: TextureCache.cpp TextureCache.h \
		GLTexture.h \
		Errors.h \
		ImageLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextureCache.o TextureCache.cpp

Timer.o: Timer.cpp Timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Timer.o Timer.cpp

Window.o: Window.cpp Window.h \
		Errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o Window.cpp

MultiScreen.o: MultiScreen.cpp MultiScreen.h \
		Camera2D.h \
		SpriteBatch.h \
		Vertex.h \
		GLSLProgram.h \
		Window.h \
		Timer.h \
		Player.h \
		ResourceManager.h \
		TextureCache.h \
		GLTexture.h \
		InputManager.h \
		Level.h \
		Errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MultiScreen.o MultiScreen.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

